services:
  caddy:
    build:
      context: ./caddy
      dockerfile: ./caddy/Dockerfile
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      # - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy_net

  whoami:
    image: traefik/whoami
    command:
      - --name=biixie
    networks:
      - proxy_net

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy_net:
    name: proxy_net
