name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Deploy Stack to Host
        uses: ibiixie/stack-deploy-action@feature/multiple-compose-inputs
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          ssh_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          file: ./compose.yaml;./compose.prod.yaml
          name: vps-infra
          mode: compose
