name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Deploy stack
        uses: cssnr/stack-deploy-action@v1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          ssh_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          file: ./compose.yaml
          name: vps-infra
          prune: true

          # Add production compose override
          args: -c ./compose.prod.yaml
